NewQLTV/Models/DOCGIA.cs
namespace NewQLTV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DOCGIA")]
    public partial class DOCGIA
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int MASINHVIEN { get; set; }

        [StringLength(100)]
        public string TENDOCGIA { get; set; }

        [StringLength(100)]
        public string GIOITINH { get; set; }

        [Column(TypeName = "date")]
        public DateTime? NGAYSINH { get; set; }

        [StringLength(100)]
        public string LOP { get; set; }

        [StringLength(100)]
        public string DIACHI { get; set; }

        public int? MATHETV { get; set; }

        [Column(TypeName = "text")]
        public string IMAGE { get; set; }

        public virtual THETHUVIEN THETHUVIEN { get; set; }
    }
}

NewQLTV/Controllers/DocgiaController.cs
    using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewQLTV.Models;

namespace QLThuVienMTA.Controllers
{
    public class DocgiaController : Controller
    {
        // GET: Docgia
        public ActionResult Index()
        {
            using (ModelDbContext Dbmodel = new ModelDbContext())
            {
                return View(Dbmodel.DOCGIAs.ToList());
            }
        }

        // GET: Docgia/Details/5
        public ActionResult Details(int id)
        {
            using (ModelDbContext modelDbContext = new ModelDbContext())
            {

                return View(modelDbContext.DOCGIAs.Where(x => x.MASINHVIEN == id).FirstOrDefault());
            }
        }

        // GET: Docgia/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Docgia/Create
        [HttpPost]
        public ActionResult Create(DOCGIA dOCGIA,  HttpPostedFileBase uploadImage)
        {
            
                string fileName = Path.GetFileNameWithoutExtension(uploadImage.FileName);
                string extension = Path.GetExtension(uploadImage.FileName);
                string filePath = Path.Combine(Server.MapPath("~/Images"), fileName);
                filePath = filePath + extension;
                uploadImage.SaveAs(filePath);
                dOCGIA.IMAGE = fileName + extension;
            

                using (ModelDbContext modelDbContext = new ModelDbContext())
                {
                    modelDbContext.DOCGIAs.Add(dOCGIA);
                    modelDbContext.SaveChanges();
                }
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            
            
        }
        
        // GET: Docgia/Edit/5
        public ActionResult Edit(int id)
        {
            using (ModelDbContext modelDbContext = new ModelDbContext())
            {

                return View(modelDbContext.DOCGIAs.Where(x => x.MASINHVIEN == id).FirstOrDefault());
            }
        }

        // POST: Docgia/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, DOCGIA dOCGIA,  HttpPostedFileBase uploadImage)
        {
            try
            {
                if (uploadImage != null && uploadImage.ContentLength > 0)
                {
                    if (dOCGIA.IMAGE != null)
                    {
                        string filePathOld = Path.Combine(Server.MapPath("~/Images"), dOCGIA.IMAGE);
                        System.IO.File.Delete(filePathOld);
                    }

                    string fileName = Path.GetFileNameWithoutExtension(uploadImage.FileName);
                    string extension = Path.GetExtension(uploadImage.FileName);
                    string filePathNew = Path.Combine(Server.MapPath("~/Images"), fileName);
                    filePathNew = filePathNew + extension;
                    uploadImage.SaveAs(filePathNew);
                    dOCGIA.IMAGE = fileName + extension;
                }
                using (ModelDbContext modelDbContext = new ModelDbContext())
                {
                    modelDbContext.Entry(dOCGIA).State = EntityState.Modified;
                    if (uploadImage == null)
                    {
                        modelDbContext.Entry(dOCGIA).Property(m => m.IMAGE).IsModified = false;
                    }
                    modelDbContext.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Docgia/Delete/5
        public ActionResult Delete(int id)
        {
            using (ModelDbContext modelDbContext = new ModelDbContext())
            {

                return View(modelDbContext.DOCGIAs.Where(x => x.MASINHVIEN == id).FirstOrDefault());
            }
        }

        // POST: Docgia/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection formCollection)
        {
            try
            {
                using (ModelDbContext modeldbContext = new ModelDbContext())
                {
                    DOCGIA dOCGIA = modeldbContext.DOCGIAs.Where(x => x.MASINHVIEN == id).FirstOrDefault();

                    if (dOCGIA.IMAGE != null)
                    {
                        string filePath = Path.Combine(Server.MapPath("~/Images"), dOCGIA.IMAGE);
                        System.IO.File.Delete(filePath);
                    }


                    modeldbContext.DOCGIAs.Remove(dOCGIA);
                    modeldbContext.SaveChanges();
                }
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

NewQLTV/Views/Docgia/Create.cshtml
@model NewQLTV.Models.DOCGIA

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Docgia", FormMethod.Post, new { enctype = "multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>DOCGIA</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.MASINHVIEN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.MASINHVIEN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MASINHVIEN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TENDOCGIA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.TENDOCGIA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TENDOCGIA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GIOITINH, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            Nam
            @Html.RadioButtonFor(model => model.GIOITINH, "Nam")
            Nữ
            @Html.RadioButtonFor(model => model.GIOITINH, "Nữ")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NGAYSINH, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.NGAYSINH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LOP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.LOP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LOP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MATHETV, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.MATHETV, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MATHETV, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-offset-2 col-md-10">
            <input type="file" name="uploadImage" value="" />
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewQLTV/Views/Docgia/Delete.cshtml
@model NewQLTV.Models.DOCGIA

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DOCGIA</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.MASINHVIEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MASINHVIEN)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TENDOCGIA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENDOCGIA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GIOITINH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIOITINH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NGAYSINH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NGAYSINH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LOP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DIACHI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATHETV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATHETV)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IMAGE)
        </dt>
        <dd>
            <img src="@Url.Content("~/Images/"+@Model.IMAGE)" alt="Alternate Text" />
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NewQLTV/Views/Docgia/Details.cshtml
@model NewQLTV.Models.DOCGIA

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DOCGIA</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.MASINHVIEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MASINHVIEN)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TENDOCGIA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENDOCGIA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GIOITINH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIOITINH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NGAYSINH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NGAYSINH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LOP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DIACHI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MATHETV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MATHETV)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IMAGE)
        </dt>

        <dd>
            <img src="@Url.Content("~/Images/"+@Model.IMAGE)" height="100px" width="100px" alt="Alternate Text" />
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MASINHVIEN }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NewQLTV/Views/Docgia/Edit.cshtml
@model NewQLTV.Models.DOCGIA

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Docgia", FormMethod.Post,new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>DOCGIA</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MASINHVIEN)

    <div class="form-group">
        @Html.LabelFor(model => model.MASINHVIEN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MASINHVIEN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MASINHVIEN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TENDOCGIA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TENDOCGIA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TENDOCGIA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GIOITINH, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GIOITINH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GIOITINH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NGAYSINH, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NGAYSINH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LOP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LOP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LOP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MATHETV, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MATHETV, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MATHETV, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img src="~/Images/@Model.IMAGE" alt="Alternate Text" style="height: 200px; width: 200px" />
        </div>
    </div>
    <div>
        New Image:
        <input type="file" name="uploadImage" value="" />
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewQLTV/Views/Docgia/Index.cshtml
@model IEnumerable<NewQLTV.Models.DOCGIA>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_layout2.cshtml";
}

<h2>Danh sách độc giả</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table" id="myTable" width="100%">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.MASINHVIEN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TENDOCGIA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GIOITINH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NGAYSINH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LOP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DIACHI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MATHETV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IMAGE)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MASINHVIEN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TENDOCGIA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GIOITINH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NGAYSINH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LOP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DIACHI)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MATHETV)
                </td>
                <td>
                    <img src="@Url.Content("~/Images/"+item.IMAGE)" height="100px" width="100px" alt="Alternate Text" />
                </td>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.MASINHVIEN }, new { @class = "btn btn-primary" }) |
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.MASINHVIEN }, new { @class = "btn btn-warning" }) |
                    @Html.ActionLink("Xóa", "Delete", new { id = item.MASINHVIEN }, new { @class = "btn btn-danger" })
                </td>
                
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.MASINHVIEN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TENDOCGIA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GIOITINH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NGAYSINH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LOP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DIACHI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MATHETV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IMAGE)
            </th>
            
            <th></th>
        </tr>
    </tfoot>
</table>